//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MonitorSystem.Web.Moldes
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class ControlValue : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“ControlValue”部分中的连接字符串初始化新 ControlValue 对象。
        /// </summary>
        public ControlValue() : base("name=ControlValue", "ControlValue")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ControlValue 对象。
        /// </summary>
        public ControlValue(string connectionString) : base(connectionString, "ControlValue")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ControlValue 对象。
        /// </summary>
        public ControlValue(EntityConnection connection) : base(connection, "ControlValue")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<t_TmpValue> t_TmpValue
        {
            get
            {
                if ((_t_TmpValue == null))
                {
                    _t_TmpValue = base.CreateObjectSet<t_TmpValue>("t_TmpValue");
                }
                return _t_TmpValue;
            }
        }
        private ObjectSet<t_TmpValue> _t_TmpValue;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<t_Channel> t_Channel
        {
            get
            {
                if ((_t_Channel == null))
                {
                    _t_Channel = base.CreateObjectSet<t_Channel>("t_Channel");
                }
                return _t_Channel;
            }
        }
        private ObjectSet<t_Channel> _t_Channel;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<t_Device> t_Device
        {
            get
            {
                if ((_t_Device == null))
                {
                    _t_Device = base.CreateObjectSet<t_Device>("t_Device");
                }
                return _t_Device;
            }
        }
        private ObjectSet<t_Device> _t_Device;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<t_Station> t_Station
        {
            get
            {
                if ((_t_Station == null))
                {
                    _t_Station = base.CreateObjectSet<t_Station>("t_Station");
                }
                return _t_Station;
            }
        }
        private ObjectSet<t_Station> _t_Station;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 t_TmpValue EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTot_TmpValue(t_TmpValue t_TmpValue)
        {
            base.AddObject("t_TmpValue", t_TmpValue);
        }
    
        /// <summary>
        /// 用于向 t_Channel EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTot_Channel(t_Channel t_Channel)
        {
            base.AddObject("t_Channel", t_Channel);
        }
    
        /// <summary>
        /// 用于向 t_Device EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTot_Device(t_Device t_Device)
        {
            base.AddObject("t_Device", t_Device);
        }
    
        /// <summary>
        /// 用于向 t_Station EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTot_Station(t_Station t_Station)
        {
            base.AddObject("t_Station", t_Station);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GDK_BCMModel", Name="t_Channel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_Channel : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 t_Channel 对象。
        /// </summary>
        /// <param name="deviceID">DeviceID 属性的初始值。</param>
        /// <param name="channelNo">ChannelNo 属性的初始值。</param>
        public static t_Channel Createt_Channel(global::System.Int32 deviceID, global::System.Int32 channelNo)
        {
            t_Channel t_Channel = new t_Channel();
            t_Channel.DeviceID = deviceID;
            t_Channel.ChannelNo = channelNo;
            return t_Channel;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DeviceID
        {
            get
            {
                return _DeviceID;
            }
            set
            {
                if (_DeviceID != value)
                {
                    OnDeviceIDChanging(value);
                    ReportPropertyChanging("DeviceID");
                    _DeviceID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DeviceID");
                    OnDeviceIDChanged();
                }
            }
        }
        private global::System.Int32 _DeviceID;
        partial void OnDeviceIDChanging(global::System.Int32 value);
        partial void OnDeviceIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ChannelNo
        {
            get
            {
                return _ChannelNo;
            }
            set
            {
                if (_ChannelNo != value)
                {
                    OnChannelNoChanging(value);
                    ReportPropertyChanging("ChannelNo");
                    _ChannelNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ChannelNo");
                    OnChannelNoChanged();
                }
            }
        }
        private global::System.Int32 _ChannelNo;
        partial void OnChannelNoChanging(global::System.Int32 value);
        partial void OnChannelNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ChannelName
        {
            get
            {
                return _ChannelName;
            }
            set
            {
                OnChannelNameChanging(value);
                ReportPropertyChanging("ChannelName");
                _ChannelName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ChannelName");
                OnChannelNameChanged();
            }
        }
        private global::System.String _ChannelName;
        partial void OnChannelNameChanging(global::System.String value);
        partial void OnChannelNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value0_Name
        {
            get
            {
                return _Value0_Name;
            }
            set
            {
                OnValue0_NameChanging(value);
                ReportPropertyChanging("Value0_Name");
                _Value0_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value0_Name");
                OnValue0_NameChanged();
            }
        }
        private global::System.String _Value0_Name;
        partial void OnValue0_NameChanging(global::System.String value);
        partial void OnValue0_NameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value1_Name
        {
            get
            {
                return _Value1_Name;
            }
            set
            {
                OnValue1_NameChanging(value);
                ReportPropertyChanging("Value1_Name");
                _Value1_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value1_Name");
                OnValue1_NameChanged();
            }
        }
        private global::System.String _Value1_Name;
        partial void OnValue1_NameChanging(global::System.String value);
        partial void OnValue1_NameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CurrentValue
        {
            get
            {
                return _CurrentValue;
            }
            set
            {
                OnCurrentValueChanging(value);
                ReportPropertyChanging("CurrentValue");
                _CurrentValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentValue");
                OnCurrentValueChanged();
            }
        }
        private Nullable<global::System.Double> _CurrentValue;
        partial void OnCurrentValueChanging(Nullable<global::System.Double> value);
        partial void OnCurrentValueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ChannelParam
        {
            get
            {
                return _ChannelParam;
            }
            set
            {
                OnChannelParamChanging(value);
                ReportPropertyChanging("ChannelParam");
                _ChannelParam = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ChannelParam");
                OnChannelParamChanged();
            }
        }
        private global::System.String _ChannelParam;
        partial void OnChannelParamChanging(global::System.String value);
        partial void OnChannelParamChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GDK_BCMModel", Name="t_Device")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_Device : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 t_Device 对象。
        /// </summary>
        /// <param name="deviceID">DeviceID 属性的初始值。</param>
        public static t_Device Createt_Device(global::System.Int32 deviceID)
        {
            t_Device t_Device = new t_Device();
            t_Device.DeviceID = deviceID;
            return t_Device;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DeviceID
        {
            get
            {
                return _DeviceID;
            }
            set
            {
                if (_DeviceID != value)
                {
                    OnDeviceIDChanging(value);
                    ReportPropertyChanging("DeviceID");
                    _DeviceID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DeviceID");
                    OnDeviceIDChanged();
                }
            }
        }
        private global::System.Int32 _DeviceID;
        partial void OnDeviceIDChanging(global::System.Int32 value);
        partial void OnDeviceIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeviceName
        {
            get
            {
                return _DeviceName;
            }
            set
            {
                OnDeviceNameChanging(value);
                ReportPropertyChanging("DeviceName");
                _DeviceName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeviceName");
                OnDeviceNameChanged();
            }
        }
        private global::System.String _DeviceName;
        partial void OnDeviceNameChanging(global::System.String value);
        partial void OnDeviceNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CommunicateType
        {
            get
            {
                return _CommunicateType;
            }
            set
            {
                OnCommunicateTypeChanging(value);
                ReportPropertyChanging("CommunicateType");
                _CommunicateType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommunicateType");
                OnCommunicateTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _CommunicateType;
        partial void OnCommunicateTypeChanging(Nullable<global::System.Int32> value);
        partial void OnCommunicateTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CommunicateID
        {
            get
            {
                return _CommunicateID;
            }
            set
            {
                OnCommunicateIDChanging(value);
                ReportPropertyChanging("CommunicateID");
                _CommunicateID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommunicateID");
                OnCommunicateIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CommunicateID;
        partial void OnCommunicateIDChanging(Nullable<global::System.Int32> value);
        partial void OnCommunicateIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubAddr
        {
            get
            {
                return _SubAddr;
            }
            set
            {
                OnSubAddrChanging(value);
                ReportPropertyChanging("SubAddr");
                _SubAddr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubAddr");
                OnSubAddrChanged();
            }
        }
        private global::System.String _SubAddr;
        partial void OnSubAddrChanging(global::System.String value);
        partial void OnSubAddrChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DeviceTypeID
        {
            get
            {
                return _DeviceTypeID;
            }
            set
            {
                OnDeviceTypeIDChanging(value);
                ReportPropertyChanging("DeviceTypeID");
                _DeviceTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeviceTypeID");
                OnDeviceTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DeviceTypeID;
        partial void OnDeviceTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnDeviceTypeIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StationID
        {
            get
            {
                return _StationID;
            }
            set
            {
                OnStationIDChanging(value);
                ReportPropertyChanging("StationID");
                _StationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StationID");
                OnStationIDChanged();
            }
        }
        private Nullable<global::System.Int32> _StationID;
        partial void OnStationIDChanging(Nullable<global::System.Int32> value);
        partial void OnStationIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StationName
        {
            get
            {
                return _StationName;
            }
            set
            {
                OnStationNameChanging(value);
                ReportPropertyChanging("StationName");
                _StationName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StationName");
                OnStationNameChanged();
            }
        }
        private global::System.String _StationName;
        partial void OnStationNameChanging(global::System.String value);
        partial void OnStationNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.String _UserId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Enable
        {
            get
            {
                return _Enable;
            }
            set
            {
                OnEnableChanging(value);
                ReportPropertyChanging("Enable");
                _Enable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Enable");
                OnEnableChanged();
            }
        }
        private Nullable<global::System.Int32> _Enable;
        partial void OnEnableChanging(Nullable<global::System.Int32> value);
        partial void OnEnableChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Port
        {
            get
            {
                return _Port;
            }
            set
            {
                OnPortChanging(value);
                ReportPropertyChanging("Port");
                _Port = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Port");
                OnPortChanged();
            }
        }
        private Nullable<global::System.Int32> _Port;
        partial void OnPortChanging(Nullable<global::System.Int32> value);
        partial void OnPortChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GDK_BCMModel", Name="t_Station")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_Station : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 t_Station 对象。
        /// </summary>
        /// <param name="stationID">StationID 属性的初始值。</param>
        public static t_Station Createt_Station(global::System.Int32 stationID)
        {
            t_Station t_Station = new t_Station();
            t_Station.StationID = stationID;
            return t_Station;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StationID
        {
            get
            {
                return _StationID;
            }
            set
            {
                if (_StationID != value)
                {
                    OnStationIDChanging(value);
                    ReportPropertyChanging("StationID");
                    _StationID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StationID");
                    OnStationIDChanged();
                }
            }
        }
        private global::System.Int32 _StationID;
        partial void OnStationIDChanging(global::System.Int32 value);
        partial void OnStationIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StationName
        {
            get
            {
                return _StationName;
            }
            set
            {
                OnStationNameChanging(value);
                ReportPropertyChanging("StationName");
                _StationName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StationName");
                OnStationNameChanged();
            }
        }
        private global::System.String _StationName;
        partial void OnStationNameChanging(global::System.String value);
        partial void OnStationNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Port
        {
            get
            {
                return _Port;
            }
            set
            {
                OnPortChanging(value);
                ReportPropertyChanging("Port");
                _Port = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Port");
                OnPortChanged();
            }
        }
        private Nullable<global::System.Int32> _Port;
        partial void OnPortChanging(Nullable<global::System.Int32> value);
        partial void OnPortChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HistoryPort
        {
            get
            {
                return _HistoryPort;
            }
            set
            {
                OnHistoryPortChanging(value);
                ReportPropertyChanging("HistoryPort");
                _HistoryPort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HistoryPort");
                OnHistoryPortChanged();
            }
        }
        private Nullable<global::System.Int32> _HistoryPort;
        partial void OnHistoryPortChanging(Nullable<global::System.Int32> value);
        partial void OnHistoryPortChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GDK_BCMModel", Name="t_TmpValue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_TmpValue : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 t_TmpValue 对象。
        /// </summary>
        /// <param name="stationID">StationID 属性的初始值。</param>
        /// <param name="deviceID">DeviceID 属性的初始值。</param>
        /// <param name="channelNO">ChannelNO 属性的初始值。</param>
        public static t_TmpValue Createt_TmpValue(global::System.Int32 stationID, global::System.Int32 deviceID, global::System.Int32 channelNO)
        {
            t_TmpValue t_TmpValue = new t_TmpValue();
            t_TmpValue.StationID = stationID;
            t_TmpValue.DeviceID = deviceID;
            t_TmpValue.ChannelNO = channelNO;
            return t_TmpValue;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StationID
        {
            get
            {
                return _StationID;
            }
            set
            {
                if (_StationID != value)
                {
                    OnStationIDChanging(value);
                    ReportPropertyChanging("StationID");
                    _StationID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StationID");
                    OnStationIDChanged();
                }
            }
        }
        private global::System.Int32 _StationID;
        partial void OnStationIDChanging(global::System.Int32 value);
        partial void OnStationIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DeviceID
        {
            get
            {
                return _DeviceID;
            }
            set
            {
                if (_DeviceID != value)
                {
                    OnDeviceIDChanging(value);
                    ReportPropertyChanging("DeviceID");
                    _DeviceID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DeviceID");
                    OnDeviceIDChanged();
                }
            }
        }
        private global::System.Int32 _DeviceID;
        partial void OnDeviceIDChanging(global::System.Int32 value);
        partial void OnDeviceIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ChannelNO
        {
            get
            {
                return _ChannelNO;
            }
            set
            {
                if (_ChannelNO != value)
                {
                    OnChannelNOChanging(value);
                    ReportPropertyChanging("ChannelNO");
                    _ChannelNO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ChannelNO");
                    OnChannelNOChanged();
                }
            }
        }
        private global::System.Int32 _ChannelNO;
        partial void OnChannelNOChanging(global::System.Int32 value);
        partial void OnChannelNOChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ChanenlSubNo
        {
            get
            {
                return _ChanenlSubNo;
            }
            set
            {
                OnChanenlSubNoChanging(value);
                ReportPropertyChanging("ChanenlSubNo");
                _ChanenlSubNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChanenlSubNo");
                OnChanenlSubNoChanged();
            }
        }
        private Nullable<global::System.Int32> _ChanenlSubNo;
        partial void OnChanenlSubNoChanging(Nullable<global::System.Int32> value);
        partial void OnChanenlSubNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MonitorValue
        {
            get
            {
                return _MonitorValue;
            }
            set
            {
                OnMonitorValueChanging(value);
                ReportPropertyChanging("MonitorValue");
                _MonitorValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MonitorValue");
                OnMonitorValueChanged();
            }
        }
        private Nullable<global::System.Double> _MonitorValue;
        partial void OnMonitorValueChanging(Nullable<global::System.Double> value);
        partial void OnMonitorValueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Flag
        {
            get
            {
                return _Flag;
            }
            set
            {
                OnFlagChanging(value);
                ReportPropertyChanging("Flag");
                _Flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Flag");
                OnFlagChanged();
            }
        }
        private Nullable<global::System.Int32> _Flag;
        partial void OnFlagChanging(Nullable<global::System.Int32> value);
        partial void OnFlagChanged();

        #endregion
    
    }

    #endregion
    
}
